on:
  workflow_dispatch:
    inputs:
      target_url:
        description: 'Link Lazi người nhận'
        required: true
      so_xu:
        description: 'Số xu'
        default: '10'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Bot
        env:
          LAZI_COOKIES_JSON: ${{ secrets.LAZI_COOKIES_JSON }}
          TARGET_URL: ${{ github.event.inputs.target_url }}
          SO_XU: ${{ github.event.inputs.so_xu }}
        run: node bot.js
